# Assignment 3

## Task 1

In [3]:
# 1
def compute5div0(a, b):
    try:
        print(a/b)
    except ZeroDivisionError:
        print(f"Error, can't divide {a} by zero")

compute5div0(5, 0)

Error, can't divide 5 by zero


In [5]:
# 2
sub = input("subjects=").split()
verbs = input("verbs=").split()
obj = input("objects=").split()
print()
for i in sub:
    for j in verbs:
        for k in obj:
            print(f"{i} {j} {k}.")

subjects=Americans Indians
verbs=play watch
objects=Baseball Cricket

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


## Task 2

In [1]:
# 1
import numpy as np
ar = list(map(int, input().split()))
v = np.array(ar, dtype=int)
print(np.vander(v))

1 2 3 4
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
